global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka_broker'
    static_configs:
      - targets: ['localhost:9090']  
    metrics_path: /metrics
    scrape_interval: 10s 

  - job_name: 'aspnetcore_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5285'] 
