#all in one
# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5244:5244"  # Backend
#       - "5000:5000"  # AI Service
#       - "3000:3000"  # Frontend
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Production
#     volumes:
#       - ./AI:/app/ai
#       - ./backend:/app/backend
#       - ./frontend:/app/frontend

#first version
# version: "3.9"

# services:
#   ai-service:
#     build:
#       context: ./AI
#       dockerfile: Dockerfile
#     image: kcanmersin/roofstock-ai-service:latest
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./AI:/app
#     depends_on:
#       - backend

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: kcanmersin/roofstock-frontend:latest
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     env_file:
#       - ./frontend/.env 
#     depends_on:
#       - ai-service
#       - backend

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     image: kcanmersin/roofstock-backend:latest
#     ports:
#       - "5244:5244"
#     volumes:
#       - ./backend:/src
#     env_file:
#       - ./backend/.env  
#second version
services:
  ai-service:
    build:
      context: ./AI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./AI:/app
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env 
    depends_on:
      - ai-service
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5244:5244"
    volumes:
      - ./backend:/src
    env_file:
      - ./backend/.env  
