
services:
  ai-service:
    build:
      context: ./AI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./AI:/app
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env 
    depends_on:
      - ai-service
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5244:5244"
    volumes:
      - ./backend:/src
    env_file:
      - ./.env  
