version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    env_file:
      - .env
    networks:
      - stockflow_network
    logging:
      driver: "json-file"
    depends_on:

networks:
  stockflow_network:
    driver: bridge

volumes:
  esdata:
