# version: '3.8'

# services:
#   api:
#     build: .
#     ports:
#       - "5000:80"
#     env_file:
#       - .env
#     networks:
#       - stockflow_network
#     logging:
#       driver: "json-file"
#     depends_on:

# networks:
#   stockflow_network:
#     driver: bridge

# volumes:
#   esdata:

version: '3.8'

services:
  api:
    build: .
    ports:
     - "5001:80"
    env_file:
      - .env
    networks:
      - stockflow_network
    logging:
      driver: "json-file"
    depends_on:
      - elasticsearch
      - logstash
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    volumes:
      - ./ELK/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - stockflow_network

  logstash:
    image: docker.elastic.co/logstash/logstash:6.0.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./ELK/logstash/:/etc/logstash/conf.d/
      -  C:/Users/KC/source/repos/StockFlow/API/Logs/:/usr/share/logstash/logs/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - stockflow_network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    volumes:
      - ./ELK/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - stockflow_network

networks:
  stockflow_network:
    driver: bridge

volumes:
  esdata:

