apiVersion: apps/v1
kind: Deployment
metadata:
  name: roofstock-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: roofstock-api
  template:
    metadata:
      labels:
        app: roofstock-api
    spec:
      containers:
      - name: roofstock-api
        image: kcanmersin/roofstock-api:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"           # Memory limit
            ephemeral-storage: "1Gi"   # Storage limit
          requests:
            memory: "256Mi"           # Memory request
            ephemeral-storage: "500Mi" # Storage request
