apiVersion: apps/v1
kind: Deployment
metadata:
  name: roofstock-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: roofstock-api
  template:
    metadata:
      labels:
        app: roofstock-api
    spec:
      containers:
      - name: roofstock-api
        image: kcanmersin/roofstock-api:latest
        ports:
        - containerPort: 80