apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      automountServiceAccountToken: false  # Disabling token mount for better security
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: "discovery.type"
          value: "single-node"
        resources:
          limits:
            memory: "2Gi"              # Memory limit
            ephemeral-storage: "5Gi"    # Storage limit
          requests:
            memory: "1Gi"              # Memory request
            ephemeral-storage: "2Gi"    # Storage request
